disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - identifier_name
    - line_length
# parameterized rules can be customized from this configuration file
line_length: 220

# These require attention in the app
function_body_length: 100
file_length: 400

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
# parameterized rules can be customized from this configuration file
# line_length: 200
